# Generated by Django 3.2.7 on 2021-09-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paitent',
            name='date',
        ),
    ]
